
linters:
  disable:
    - unused
    - govet

issues:
  exclude-rules:
    - path: internal/util/media/converter.go
      linters:
        - gosec
    - path: internal/api/handler/response_helpers.go
      linters:
        - unused
    - path: internal/integrations/chatwoot/service/cache.go
      linters:
        - unused

