run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Bugs - CRITICAL
    - bodyclose        # HTTP response body must be closed
    - durationcheck    # check for two durations multiplied together
    - errcheck         # check for unchecked errors
    - gosec            # security problems
    - nilerr           # returning nil after checking err != nil
    - sqlclosecheck    # ensure sql.Rows/Stmt are closed

    # Style & Quality
    - gofmt            # formatting
    - goimports        # imports ordering
    - misspell         # spelling mistakes
    - unused           # unused code
    - staticcheck      # many checks

linters-settings:
  gosec:
    excludes:
      - G104  # audit errors not checked (handled by errcheck)
      - G304  # file inclusion via variable (common in file handlers)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    - path: docs/
      linters:
        - all

    # G201 false positives - these use parameterized placeholders ($1, $2), not user data
    - path: internal/integrations/chatwoot/repository/chatwoot_db.go
      linters:
        - gosec
      text: "G201"

    - path: internal/integrations/chatwoot/sync/repository.go
      linters:
        - gosec
      text: "G201"

    # G115 integer overflow - values are from protobuf and are always within safe range
    - linters:
        - gosec
      text: "G115"

    # G107 HTTP request with variable URL - these are API calls to configured endpoints
    - linters:
        - gosec
      text: "G107"
