# GoReleaser configuration for OnWapp
# Documentation: https://goreleaser.com

version: 2

project_name: onwapp

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: onwapp
    main: ./cmd/onwapp
    binary: onwapp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X onwapp/internal/version.Version={{.Version}}
      - -X onwapp/internal/version.GitCommit={{.Commit}}
      - -X onwapp/internal/version.BuildDate={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE*
      - docs/*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Refactoring"
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Other"
      order: 999

dockers:
  - image_templates:
      - "docker.io/felipyfgs17/onwapp:{{ .Version }}"
      - "docker.io/felipyfgs17/onwapp:latest"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    use: buildx
    extra_files:
      - go.mod
      - go.sum
      - cmd
      - internal
      - docs
      - painel
      - docker/entrypoint.sh
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: onwapp
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## OnWapp {{ .Version }}
    
    WhatsApp API with Chatwoot Integration
  footer: |
    ---
    
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/onwapp/compare/{{ .PreviousTag }}...{{ .Tag }}

announce:
  skip: true
